# Generated by Django 4.1.1 on 2022-09-20 14:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogos',
            name='game_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
