# Generated by Django 4.1.1 on 2022-09-20 16:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0002_alter_jogos_game_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogos',
            name='game_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
