# Generated by Django 4.1.1 on 2022-09-20 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0003_alter_jogos_game_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogos',
            name='consolidado',
            field=models.JSONField(null=True),
        ),
    ]
